### ISSUE TITLE
RLC Members Roster Report

### ISSUE THREAD

**Issue by csdetschjr** [AppStateESS/homestead#1059]
Create a roster of all RLC members and their roommates with the following information:
 - Assignment Hall and Room
 - Name
 - Username
 - Banner Id
 - Community name

This report needs to also be exportable to a spreadsheet.

**Comment by jlbooker** [comment]
Tested. Works for me. Email RLC coordinator who requested it for his approval. :+1:

**Comment by jlbooker** [comment]
Got approval from RLC coordinator. Ready to go.
