### ISSUE TITLE
Refresh Cache Nightly

### ISSUE THREAD

**Issue by jlbooker** [AppStateESS/homestead#937]
Create a script which will query the student info web service for all students who have applied for the current or future terms, and all students who have been assigned for all current or future terms. Use the StudentFactory and/or StudentDataProvider classes so that all caches are refreshed nightly. Could probably also truncate the cache tables and tell APC to clear user cache before starting the refresh.

Also, this will likely involve rewriting parts of the Pulse module, so as not to make a database entry every night (need just one database entry specifying to run the job nightly, and keep it's current status... last started and last completed timestamps).

**Comment by Stardog** [comment]
Completed via da1fa3a3ff00361c278e1240f179a2f731d66e7f

**Comment by jlbooker** [comment]
Can't really test this on r6test, as the banner web service isn't looking at a recent snapshot. This means most of the current students wouldn't exist. Will test in production...
